/*
	(c) 2004: Jelmer Vernooij <jelmer@samba.org>

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#include <stdio.h>
#include <errno.h>
#include <popt.h>
#include <string.h>
#include "gp.h"

#ifndef HAVE_CONFIG
#  include "config.h"
#endif

#define LILYPOND_VERSION "2.4"

static void ly_write_header(FILE *out, struct gpf *gpf)
{
	int i;
	fprintf(out, "\\header {\n");
	fprintf(out, "\ttitle = \"%s\"\n", gpf->title);
	fprintf(out, "\tartist = \"%s\"\n", gpf->artist);
	fprintf(out, "\talbum = \"%s\"\n", gpf->album);
	fprintf(out, "\tsubtitle = \"%s\"\n", gpf->subtitle);
	fprintf(out, "\tenteredby = \"%s\"\n", gpf->tab_by);
	fprintf(out, "\tinstruction = \"%s\"\n", gpf->instruction);
	fprintf(out, "\tcomposer = \"%s\"\n", gpf->author);
	fprintf(out, "\tcopyright = \"%s\"\n", gpf->copyright);

	for (i = 0; i < gpf->notice_num_lines; i++)
	{
		fprintf(out, "\t%% %s\n", gpf->notice[i]);
	}

	fprintf(out, "}\n\n");
}

int main(int argc, const char **argv) 
{
	FILE *out;
	struct gpf *ret;
	int c;
	int version = 0;
	int quiet = 0;
	const char *input;
	char *output = NULL;
	poptContext pc;
	struct poptOption options[] = {
		POPT_AUTOHELP
		{"outputfile", 'o', POPT_ARG_STRING, &output, 0, "Write to specified file", "FILE" },
		{"quiet", 'q', POPT_ARG_NONE, &quiet, 1, "Be quiet (no output to stderr)" },
		{"version", 'v', POPT_ARG_NONE, &version, 'v', "Show version information" },
		POPT_TABLEEND
	};

	pc = poptGetContext(argv[0], argc, argv, options, 0);
	poptSetOtherOptionHelp(pc, "file.ptb");
	while((c = poptGetNextOpt(pc)) >= 0) {
		switch(c) {
		case 'v':
			printf("gp2ly Version "PACKAGE_VERSION"\n");
			printf("(C) 2004 Jelmer Vernooij <jelmer@samba.org>\n");
			exit(0);
			break;
		}
	}
			
	if(!poptPeekArg(pc)) {
		poptPrintUsage(pc, stderr, 0);
		return -1;
	}
	input = poptGetArg(pc);
	
	if (!quiet) fprintf(stderr, "Parsing %s... \n", input);
					
	ret = gp_read_file(input);
	
	if(!ret) {
		perror("Read error: ");
		return -1;
	} 

	if(!output) {
		int baselength = strlen(input);
		if (!strncmp(input + strlen(input) - 4, ".gp", 3)) {
			baselength -= 4;
		}
		output = malloc(baselength + 5);
		strncpy(output, input, baselength);
		strcpy(output + baselength, ".ly");
	}

	if (!quiet) fprintf(stderr, "Generating lilypond file in %s...\n", output);

	if (!strcmp(output, "-")) {
		out = stdout; 
	} else {
		out = fopen(output, "w+");
		if(!out) {
			perror("open");
			return -1;
		}
	}

	fprintf(out, "%% Generated by gp2ly (C) 2004 Jelmer Vernooij <jelmer@samba.org>\n");
	fprintf(out, "%% See http://jelmer.vernstok.nl/oss/ptabtools/ for more info\n\n");
	
	fprintf(out, "\\version \""LILYPOND_VERSION"\"\n");

	ly_write_header(out, ret);
		
	fprintf(out, "\n\\score { << \n");

	fprintf(out, "\t\\context ChordNames {\n");
	fprintf(out, "\t}\n");

	fprintf(out, "\t\\context StaffGroup <<\n");
	fprintf(out, "\t\t\\context Staff { \n");
	fprintf(out, "\t\t}\n");
	fprintf(out, "\t\\context TabStaff { \n");
	fprintf(out, "\t\t}\n");
	fprintf(out, "\t>>\n");

	fprintf(out, "\t>>\n");
	
	fprintf(out, "\t\\layout { }\n");
	fprintf(out, "\t\\midi { }\n");
	fprintf(out, "} \n");

	if(output)fclose(out);
	
	return (ret?0:1);
}
