/*
	(c) 2004: Jelmer Vernooij <jelmer@samba.org>

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#include <stdio.h>
#include <errno.h>
#include <popt.h>
#include <string.h>
#include "ptb.h"

#define LILYPOND_VERSION "2.2"

char *note_names[12] = {
	 "a", "ais", "b", "c", "cis", "d", "dis", "e", "f", "fis", "g", "gis"
};

char *ly_escape(char *data)
{
	static char tmp[2000];
	int i, j = 0;
	for(i = 0; data[i]; i++) {
		switch(data[i]) {
		case '&':
			tmp[j] = '\\'; j++;
		default:
			tmp[j] = data[i];j++;
		}
	}
	tmp[j] = '\0';
	return tmp;
}

void ly_write_header(FILE *out, struct ptbf *ret) 
{
	fprintf(out, "\\header {\n");
	if(ret->hdr.classification == CLASSIFICATION_SONG) {
		if(ret->hdr.class_info.song.title) 	fprintf(out, "  title = \"%s\"\n", ly_escape(ret->hdr.class_info.song.title));
		if(ret->hdr.class_info.song.music_by) fprintf(out, "  composer = \"%s\"\n", ly_escape(ret->hdr.class_info.song.music_by));
		if(ret->hdr.class_info.song.words_by) fprintf(out, "  poet = \"%s\"\n", ly_escape(ret->hdr.class_info.song.words_by));
		if(ret->hdr.class_info.song.copyright) fprintf(out, "  copyright = \"%s\"\n", ly_escape(ret->hdr.class_info.song.copyright));
		if(ret->hdr.class_info.song.guitar_transcribed_by) fprintf(out, "  arranger = \"%s\"\n", ly_escape(ret->hdr.class_info.song.guitar_transcribed_by));
		if(ret->hdr.class_info.song.artist) fprintf(out, "  subtitle = \"As recorded by %s\"\n", ly_escape(ret->hdr.class_info.song.artist));
		if(ret->hdr.class_info.song.release_type == RELEASE_TYPE_PR_AUDIO &&
		   ret->hdr.class_info.song.release_info.pr_audio.album_title) fprintf(out, "  subsubtitle = \"From the %d album %s\"\n", ret->hdr.class_info.song.release_info.pr_audio.year, ly_escape(ret->hdr.class_info.song.release_info.pr_audio.album_title));
	} else if(ret->hdr.classification == CLASSIFICATION_LESSON) {
		if(ret->hdr.class_info.lesson.title) 	fprintf(out, "  title = \"%s\"\n", ly_escape(ret->hdr.class_info.lesson.title));
		if(ret->hdr.class_info.lesson.artist) fprintf(out, "  composer = \"%s\"\n", ly_escape(ret->hdr.class_info.lesson.artist));
		if(ret->hdr.class_info.lesson.author) fprintf(out, "  arranger = \"%s\"\n", ly_escape(ret->hdr.class_info.lesson.author));
		if(ret->hdr.class_info.lesson.copyright) fprintf(out, "  copyright = \"%s\"\n", ly_escape(ret->hdr.class_info.lesson.copyright));
	}
	fprintf(out, "tagline = \"Engraved by lilypond, generated by ptb2ly\"\n");
	fprintf(out, "}\n");
}

void ly_write_chordname_full(FILE *out, guint8 base, guint8 properties, guint8 additions, int len)
{
	fprintf(out, "%s", ptb_get_tone_full(base));
	if(len) {
		int i, newl, dots;
		for(i = 1; i < 64; i*=2) {
			if(len >= i && len < i*2) {
				newl = i;
				dots = 0;
				if(newl * 1.5 == len) dots = 1;
				if(newl * 1.75 == len) dots = 2;
				break;
			}
		}
		fprintf(out, "%d", newl);
		for(i = 0; i < dots; i++)fprintf(out, ".");
	}

	if(properties & CHORDTEXT_PROPERTY_FORMULA_MAJ7 ||
	   properties & CHORDTEXT_PROPERTY_FORMULA_M ||
	   additions & CHORDTEXT_ADD_9) {
		fprintf(out, ":");
		if(additions & CHORDTEXT_ADD_9)
			fprintf(out, "9");

		if(properties & CHORDTEXT_PROPERTY_FORMULA_MAJ7)fprintf(out, "maj7");
		if(properties & CHORDTEXT_PROPERTY_FORMULA_M)fprintf(out, "m");
	}
}

void ly_write_chordtext_helper(FILE *out, struct ptb_chordtext *name, int length)
{
	if(name->properties & CHORDTEXT_PROPERTY_NOCHORD) {
		//FIXME:fprintf(out, "N.C.");
	} 

	/*
	if(name->properties & CHORDTEXT_PROPERTY_PARENTHESES) {
		fprintf(out, "(");
	}*/

	if(!(name->properties & CHORDTEXT_PROPERTY_NOCHORD) || 
	   (name->properties & CHORDTEXT_PROPERTY_PARENTHESES)) { 
		ly_write_chordname_full(out, name->name[1], name->properties, name->additions, length);

		/* Different bass note */
		if(name->name[0] != name->name[1] && name->name[0] >= 16 && name->name[0] <= 28) {
			fprintf(out, "/+");
			ly_write_chordname_full(out, name->name[0], 0, 0, 0);
		}

	} /*
	if(name->properties & CHORDTEXT_PROPERTY_PARENTHESES) {
		fprintf(out, ")");
	} */

	
	fprintf(out, " ");

}

void ly_write_chordtext(FILE *out, struct ptb_section *section, struct ptb_chordtext *name, struct ptb_chordtext *next)
{
	/* Length:
	 *  - Figure out the offset of the next chord, if any
	 *  - Get the length of the notes between the next chord and this chord
	 *  - We've got our length!
	 */

	int bars, length, i;
	ptb_get_position_difference(section, name->offset, next?next->offset:0xffff, &bars, &length);
	for(i = 0; i < bars; i++) 
		ly_write_chordtext_helper(out, name, 1);
	if(length)
		ly_write_chordtext_helper(out, name, length);
}

static float previous = 0.0;

void ly_write_position(FILE *out, struct ptb_position *pos)
{
	float this = 0.0;
	char print_length = 0;
	GList *gl = pos->linedatas;
	int l = g_list_length(pos->linedatas);

	this = pos->length * (pos->dots & POSITION_DOTS_1?1.5:1.0) 
		* (pos->dots & POSITION_DOTS_2?1.5*1.5:1.0);
	
	if(this != previous) {
		print_length = 1;
		previous = this;
	}

	fprintf(out, " ");

	if(l == 0) {/* Rest */
		fprintf(out, " r");
	}

	/* Multiple notes */
	if(l > 1 || print_length) fprintf(out, " <");

	while(gl) {
		struct ptb_linedata *d = gl->data;
		int note = d->detailed.fret;
		int i;
		int octave;
#define DEFAULT_OCTAVE 4
		
		switch(d->detailed.string) {
		case 0: note+= 64; break;
		case 1: note+= 59; break;
		case 2: note+= 55; break;
		case 3: note+= 50; break;
		case 4: note+= 45; break;
		case 5: note+= 40; break;
		default:fprintf(stderr, "Unknown string %d", d->detailed.string);
		}
		
		fprintf(out, "%s", note_names[(note+3)%12]);

		octave = note / 12;

		for(i = octave; i < DEFAULT_OCTAVE; i++) fprintf(out, ",");
		for(i = DEFAULT_OCTAVE; i < octave; i++) fprintf(out, "'");

		if(pos->palm_mute & POSITION_STACCATO) 
			fprintf(out, "-.");

		if(pos->palm_mute & POSITION_ACCENT)
			fprintf(out, "->");

		fprintf(out, "\\%d", d->detailed.string+1);
		if(pos->properties & LINEDATA_PROPERTY_TIE) fprintf(out, " ~");
		gl = gl->next;
		if(gl) fprintf(out, " ");
	}

	/* Multiple notes */
	if(l > 1 || print_length) fprintf(out, ">");

	/* String */
	if(print_length) {
		fprintf(out, "%d", pos->length);
		if(pos->dots & POSITION_DOTS_1) fprintf(out, ".");
		if(pos->dots & POSITION_DOTS_2) fprintf(out, "..");
	}

	if(pos->properties & POSITION_PROPERTY_FIRST_IN_BEAM)
		fprintf(out, "[");


	if(pos->properties & POSITION_PROPERTY_LAST_IN_BEAM)
		fprintf(out, "]");
}

void ly_write_staff(FILE *out, struct ptb_staff *s, struct ptb_section *section) 
{
	GList *gl;
	int i;

	fprintf(out, "\t\\new StaffGroup {\n");
	fprintf(out, "\t\t\\simultaneous {\n");
	fprintf(out, "\t\t\t\\new Staff {\n");
	if(s->properties & STAFF_TYPE_BASS_KEY)
		fprintf(out, "\t\t\t\t\\clef F\n");
	else
		fprintf(out, "\t\t\t\t\\clef \"G_8\"\n");

//	fprintf(out, "\\time %d/%d\n", section->detailed.beat, section->detailed.beat_value);

	fprintf(out, "\t\t\t\t\\notes {\n");
	fprintf(out, "\t\t\t\t\t\t");
	previous = 0.0;
	for(i = 0; i < 2; i++) {
		gl = s->positions[i];
		while(gl) {
			ly_write_position(out, (struct ptb_position *)gl->data);
			gl = gl->next;
		}
	}
	fprintf(out, "\n");
	fprintf(out, "\t\t\t\t}\n");

	fprintf(out, "\t\t\t}\n");
	fprintf(out, "\t\t\t\\new TabStaff {\n");
	fprintf(out, "\t\t\t\t\\notes {\n");
	fprintf(out, "\t\t\t\t\t");
	for(i = 0; i < 2; i++) {
		gl = s->positions[i];
		while(gl) {
			ly_write_position(out, (struct ptb_position *)gl->data);
			gl = gl->next;
		}
	}
	fprintf(out, "\n");
	fprintf(out, "\t\t\t\t}\n");


	fprintf(out,"\t\t\t}\n");
	fprintf(out,"\t\t}\n");
	fprintf(out, "\t}\n");
}

void ly_write_section(FILE *out, struct ptb_section *s) 
{
	GList *gl;

	fprintf(out, "\n\\score { << \n");
	gl = s->chordtexts;
	if(gl) {
		int bars, length, i;
		fprintf(out, "\t\\context ChordNames \\chords {\n");
		fprintf(out, "\t\t");
		ptb_get_position_difference(s, 0, ((struct ptb_chordtext *)gl->data)->offset, &bars, &length);
		for(i = 0; i < bars; i++) fprintf(out, "r1 ");
		if(length) fprintf(out, "r%d ", length);

		while(gl) {
			ly_write_chordtext(out, s, (struct ptb_chordtext *)gl->data, (struct ptb_chordtext *)gl->next?gl->next->data:NULL);
			gl = gl->next;
		}

		fprintf(out, "\n\t}\n");
	}

	gl = s->staffs;
	
	while(gl) {
		ly_write_staff(out, (struct ptb_staff *)gl->data, s);
		gl = gl->next;
	}


	fprintf(out, "\t>>\n");

	fprintf(out, "\t\\paper { }\n");
	fprintf(out, "\t\\midi { }\n");
	fprintf(out, "} \n");
}

int ly_write_lyrics(FILE *out, struct ptbf *ret)
{
	if(ret->hdr.classification != CLASSIFICATION_SONG || !ret->hdr.class_info.song.lyrics) return 0;
	fprintf(out, "text = \\lyrics {\n");
	fprintf(out, "\t%s\n", ret->hdr.class_info.song.lyrics);
	fprintf(out, "%s\n", "}\n");
	return 1;
}

int main(int argc, const char **argv) 
{
	FILE *out;
	int have_lyrics;
	struct ptbf *ret;
	int debugging = 0;
	GList *gl;
	int instrument = 0;
	int c, i = 0;
	int version = 0;
	int quiet = 0;
	int num_sections = 0;
	const char *input;
	char *output = NULL;
	poptContext pc;
	struct poptOption options[] = {
		POPT_AUTOHELP
		{"debug", 'd', POPT_ARG_NONE, &debugging, 0, "Turn on debugging output" },
		{"outputfile", 'o', POPT_ARG_STRING, &output, 0, "Write to specified file", "FILE" },
		{"regular", 'r', POPT_ARG_NONE, &instrument, 0, "Write tabs for regular guitar" },
		{"bass", 'b', POPT_ARG_NONE, &instrument, 1, "Write tabs for bass guitar"},
		{"sections", 's', POPT_ARG_INT, &num_sections, 0, "Write only X sections (0 for all)", "SECTIONS" },
		{"quiet", 'q', POPT_ARG_NONE, &quiet, 1, "Be quiet (no output to stderr)" },
		{"version", 'v', POPT_ARG_NONE, &version, 'v', "Show version information" },
		POPT_TABLEEND
	};

	pc = poptGetContext(argv[0], argc, argv, options, 0);
	poptSetOtherOptionHelp(pc, "file.ptb");
	while((c = poptGetNextOpt(pc)) >= 0) {
		switch(c) {
		case 'v':
			printf("ptb2ly Version "PTB_VERSION"\n");
			printf("(C) 2004 Jelmer Vernooij <jelmer@samba.org>\n");
			exit(0);
			break;
		}
	}
			
	ptb_set_debug(debugging);
	
	if(!poptPeekArg(pc)) {
		poptPrintUsage(pc, stderr, 0);
		return -1;
	}
	input = poptGetArg(pc);
	
	if (!quiet) fprintf(stderr, "Parsing %s... \n", input);
					
	ret = ptb_read_file(input);
	
	if(!ret) {
		perror("Read error: ");
		return -1;
	} 

	if(!output) {
		int baselength = strlen(input);
		if (!strcmp(input + strlen(input) - 4, ".ptb")) {
			baselength -= 4;
		}
		output = malloc(baselength + 5);
		strncpy(output, input, baselength);
		strcpy(output + baselength, ".ly");
	}

	if (!quiet) fprintf(stderr, "Generating lilypond file in %s...\n", output);

	if (!strcmp(output, "-")) {
		out = stdout; 
	} else {
		out = fopen(output, "w+");
		if(!out) {
			perror("open");
			return -1;
		}
	}
	
	fprintf(out, "%% Generated by ptb2ly (C) 2004 Jelmer Vernooij <jelmer@samba.org>\n");
	fprintf(out, "%% See http://jelmer.vernstok.nl/oss/ptabtools/ for more info\n\n");
	fprintf(out, "\\version \""LILYPOND_VERSION"\"\n");
		
	ly_write_header(out, ret);
	have_lyrics = ly_write_lyrics(out, ret);
	
	gl = ret->instrument[instrument].sections;
	while(gl) {
		if(++i > num_sections && num_sections) break;
		ly_write_section(out, (struct ptb_section *)gl->data);
		gl = gl->next;
	}


	if(output)fclose(out);
	
	return (ret?0:1);
}
