.TH ptbdict 1 "23 February 2005"
.SH NAME
ptbdict \- Display and edit PowerTab Tuning Dictionary files
.SH SYNOPSIS
.PP
.B ptbdict
[-v|-a|-d]
\fItunings.dat\fP
\fI[tuning-name] ...\fP
.RI
.SH DESCRIPTION
\fBptbdict\fP is a program that can display PowerTab tuning 
dictionary files (usually called tunings.dat) and add or delete 
entries from such files.

.PP
When no options are given and only one argument, ptbdict displays all tunings. 
If one or more tuning names are supplied, only the tunings with the 
specified names are displayed.

.PP
.SH OPTIONS
.PP
.IP "--help"
Show all available options.
.IP "-d"
Delete specified tuning(s).
.IP "-a"
Add specified tuning(s).
.SH "SEE ALSO"
.BR https://samba.org/~jelmer/ptabtools
.PP
.BR http://www.power-tab.net/

.SH BUGS
.PP
Please report any bugs to Jelmer Vernooij at \fBjelmer@samba.org\fP.
.SH LICENSE
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
\fBWITHOUT ANY WARRANTY\fR; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.
.PP
You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple PLace, Suite 330, Boston, MA  02111-1307  USA
.SH AUTHOR
.BR
 Jelmer Vernooij <jelmer@samba.org>
